global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#all-weather-monitoring-workspace'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: |
           *Alert:* {{ .CommonLabels.alertname }}
           *Severity:* {{ .Labels.severity }}
           *Summary:* {{ .Annotations.summary }}
           *Description:* {{ .Annotations.description }}
