global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: <Telegram Bot Token>
        chat_id: <Group_chat_id>
        send_resolved: true
        message: |
          Alert: {{ .CommonLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}
