global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: '#alerts'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: |
           *Alert:* {{ .CommonLabels.alertname }}
           *Severity:* {{ .CommonLabels.severity }}
           *Summary:* {{ .CommonAnnotations.summary }}
           *Description:* {{ .CommonAnnotations.description }}
