

services:   #κάθε εργασία είναι χωρισμένη σε services
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml   #σύνδεση τοπικού αρχείου promitheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml  #σύνδεση τοπικού αρχείου alert_rules.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"   #αρχείο διαμόρφωσης(configuration file) prometheus.yml
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    env_file:
      - .env
    ports:
      - "9093:9093"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Mariosgr12
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana   

volumes:
  grafana-data:   

networks:
  monitoring:
    driver: bridge    
