global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"  

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'flask_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flaskapp-weather-flask-app-nv4xfwe7z5jli.azurewebsites.net']  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

